logins:
  build: .
  dockerfile: Dockerfile
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - ".:/code"
    - "../dev-nginx:/dev-nginx"
    - "$HOME/.aws/:/root/.aws:ro"
  environment:
    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
    AWS_SESSION_TOKEN: $AWS_SESSION_TOKEN
  entrypoint: /code/entrypoint.sh
